version: "3.6"
services:
  nginx:
    image: nginx:latest
    container_name: platform-nginx
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./:/var/www/html:rw,cached
      - ./docker/nginx/certs:/etc/certs
    depends_on:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: platform-mysql
    command: --general-log=1 --general-log-file=/tmp/mysql.log
    volumes:
      - platform-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=platform
    restart: always
    ports:
      - "3308:3306"

  wordpress:
    container_name: platform-wordpress
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME=platform
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_TABLE_PREFIX=wp_
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  composer:
    image: composer
    working_dir: /var/www/html
    restart: "no"
    volumes:
      - ./:/var/www/html:rw,cached

volumes:
  platform-mysql:
