<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
print_execution_time("Autoload");

require_once dirname(__DIR__) . '/config/application.php';
print_execution_time("Application");

require_once ABSPATH . 'wp-settings.php';
print_execution_time("WP Settings");

error_reporting(E_ALL ^ E_DEPRECATED);
print_execution_time("WP Config");
